name: build

on:
  workflow_dispatch:
  #push:
    #paths-ignore:
      #- "**.md"
      #- LICENSE
      #- .github/FUNDING.yml
    #branches: [main, dev]
  #pull_request:
    #paths-ignore:
      #- "**.md"
      #- LICENSE
      #- .github/FUNDING.yml
    #branches: [main]
env:
  BUILD_TOML: configs/normal/win_rg.build.toml
  OS: windows
  SIZE: 36

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Installing Node Dependencies
        run: |
          rm -rf node_modules yarn.lock
          yarn install --frozen-lockfile
        continue-on-error: false

      - name: Print cbmp version
        run: npx cbmp --version

      - name: Rendering Bitmaps
        run: yarn render
        continue-on-error: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Installing PyPi Dependencies
        run: python -m pip install --upgrade pip clickgen
        continue-on-error: false

      - name: Print clickgen Version
        run: |
          clickgen --version
          ctgen --version

      - name: Custom Bibata Cursors Size & Color
        run: ctgen $BUILD_TOML -s $SIZE -p $OS -d 'bitmaps/Bibata-Modern-Ice' -o 'out' -n 'Bibata-Modern-Ice' -c 'White and rounded egde Bibata cursors with size $SIZE'

      - name: Building Bibata Cursors
        run: yarn build

      - name: Upload Build Cursor Bibata
        uses: actions/upload-artifact@main
        with:
          name:  Bibata_Windows
          path: ./out
